name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  bug-tracker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bug Tracker
        uses: actions/checkout@v5

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test